# Generated by Django 2.0.3 on 2018-03-12 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.CharField(default='test', max_length=32),
            preserve_default=False,
        ),
    ]
