# Generated by Django 2.0.3 on 2018-03-13 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20180313_0426'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
