# Generated by Django 2.0.3 on 2018-03-13 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='visible_in_menu',
            field=models.BooleanField(default=False),
        ),
    ]
