# Generated by Django 2.0.3 on 2018-03-13 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_category_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='visible_in_menu',
        ),
    ]
