# Generated by Django 2.0.3 on 2018-03-13 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_remove_category_visible_in_menu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='Owner',
            new_name='owner',
        ),
    ]
