# Generated by Django 2.0.3 on 2018-03-15 13:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_auto_20180315_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='order',
            field=models.IntegerField(default=0, help_text='For menu order. It is recommended that you use increments of 10 as to allow for easy re-ordering of menu items. A value of 0 indicates that it is not a menu item.'),
        ),
        migrations.AddField(
            model_name='article',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Optional. Used for menu or breadcrumb trail.', null=True, on_delete=django.db.models.deletion.CASCADE, to='website.Article'),
        ),
        migrations.AlterField(
            model_name='article',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Anyone is this group can edit.', null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='article',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='The owner can edit.', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
