# Generated by Django 2.0.3 on 2018-03-15 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_auto_20180315_1326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='stub',
        ),
        migrations.AddField(
            model_name='article',
            name='page_type',
            field=models.CharField(choices=[('Article', 'article'), ('Table Of Contents', 'table_of_contents')], default='article', max_length=32),
        ),
        migrations.AlterField(
            model_name='article',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Optional. Used for menu or breadcrumb trail. Empty indicates top level.', null=True, on_delete=django.db.models.deletion.CASCADE, to='website.Article'),
        ),
    ]
