# Generated by Django 2.0.3 on 2018-03-15 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_auto_20180315_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='page_type',
            field=models.CharField(choices=[('link', 'Link'), ('article', 'Article'), ('table_of_contents', 'Table Of Contents')], default='article', max_length=32),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.CharField(blank=True, help_text='Must be one lowercase word. You must populate either slug or link for proper functionality.', max_length=32, null=True, unique=True),
        ),
    ]
