# Generated by Django 2.0.3 on 2018-03-15 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_auto_20180315_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.CharField(default='1', help_text='Must be one lowercase word. You must populate either slug or link for proper functionality.', max_length=32, unique=True),
            preserve_default=False,
        ),
    ]
