# Generated by Django 2.0.3 on 2018-04-09 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_globalcontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalcontent',
            name='name',
            field=models.CharField(choices=[('link', 'Link'), ('article', 'Article'), ('table_of_contents', 'Table Of Contents')], default='article', max_length=32),
        ),
    ]
